INSERT INTO BRAND(NAME) VALUES
  ('DKNY'),
  ('KATE SPADE'),
  ('GUESS'),
  ('RALPH LAUREN');

  INSERT INTO COLOR(NAME)  VALUES
  ('BLACK'),
  ('WHITE'),
  ('BLUE'),
  ('RED');

INSERT INTO SIZE(CODE)  VALUES
('S'),
('M'),
('ONE_SIZE')
('L');

INSERT INTO SELLER (SELLER_NAME) VALUES
('6PM'),
('ZAPPOS');

  INSERT INTO PRODUCT_CATEGORY(NAME) VALUES
  ('TOP'),
  ('BOTTOM'),
  ('ACCESSORIES');

  INSERT INTO PRODUCT(
  ID,
  NAME,
  PRODUCT_CATEGORY_ID) VALUES
  (1,'BLOUSE',1),
  (2,'JEANS',2),
  (3,'SWEATER',1),
  (4,'GLOVES',3),
  (5,'JACKET',1);


 INSERT INTO PRODUCT_SELLER (quantity, PRICE, SKU, PRODUCT_ID, SELLER_ID, BRAND_ID, COLOR_ID, SIZE_ID) VALUES
   (3, 36, 'SKU68593', 1, 2, 4, 4, 3 ),
   (1, 255, 'SKU35789', 2, 1, 3, 2, 1 ),
   (7, 99, 'SKU14569', 3, 1, 1, 3, 2 ),
   (10, 50, 'SKU87532', 4, 1, 2, 1, 3 ),
   (5, 88, 'SKU95137', 5, 2, 1, 4, 4 );